WeatherStack Core: src/core/args.cpp File Reference
args.cpp File Reference
#include <malloc.h>
#include <string.h>
#include <ws_core/ws.h>
#include <ws_core/types/args.h>
#include <iostream>
Namespaces
namespace WS_Core
namespace WS_Core::Args
Functions
void str_to_lower (const char *o, char *n)
bool str_to_bool (const char *str)
bool str_is_bool (const char *str)
bool starts_with (const char *prefix, const char *str)
bool remove_first (const char *o, char *n)
bool find_arg (const char *name, Args::Arg *out)
Function Documentation
find_arg()
bool find_arg (const char * name, Args::Arg * out)
Definition at line 220 of file args.cpp.
{
    // Check if it either begins with the long
    // or short argument thing
    // and because Windows just has to be unique
    // just check both on Windows
    char* arg = (char*)malloc(sizeof(name));
    bool kind = remove_first(name, arg);
    if(arg == NULL) {
        // If arg is NULL, remove_first just didn't
        // like it
        out = NULL;
        return false;
    }
    for(int i = 0; i < Args::args.size(); i++) {
        bool is_arg = false;
    #if defined(_WIN32) || defined(_WIN64)
        // Completely discard "kind"
        if(strcmp(Args::args[i].arg_long, name) == 1 ||
            strcmp(Args::args[i].arg_short, name) == 1) {
            is_arg = true;
        }
    #else
        if(kind &&
            strcmp(Args::args[i].arg_long, name) == 1) {
            is_arg = true;
        } else if(strcmp(Args::args[i].arg_short, name) == 1) {
            is_arg = true;
        }
    #endif
        if(is_arg) {
            free(arg);
            memcpy(out, &Args::args[i], sizeof(Args::Arg));
            return true;
        }
    }
    free(arg);
    out = NULL;
    return NULL;
}
References WS_Core::Args::args, and remove_first().
Referenced by WS_Core::Args::parse_args().
remove_first()
bool remove_first (const char * o, char * n)
Definition at line 193 of file args.cpp.
{
    #if defined(_WIN32) || defined(_WIN64)
    if(starts_with(WS_CLI_ARG_LONG_BEGIN, o)) {
        strcpy(n, o);
        n++;
    } else {
        n = NULL;
        return false;
    }
    return false;
    #else
    bool kind = false;
    if(starts_with(WS_CLI_ARG_LONG_BEGIN, o)) {
        kind = true;
        strcpy(n, o);
        n += 2;
    } else if(starts_with(WS_CLI_ARG_SHORT_BEGIN, o)) {
        strcpy(n, o);
        n++;
    } else {
        n = NULL;
        return false;
    }
    return kind;
    #endif
}
References starts_with(), WS_CLI_ARG_LONG_BEGIN, and WS_CLI_ARG_SHORT_BEGIN.
Referenced by find_arg().
starts_with()
bool starts_with (const char * prefix, const char * str)
Definition at line 187 of file args.cpp.
{
    return strstr(str, prefix) == str;
}
Referenced by remove_first().
str_is_bool()
bool str_is_bool (const char * str)
Definition at line 178 of file args.cpp.
{
    char* lower = (char*)malloc(sizeof(str));
    str_to_lower(str, lower);
    return strcmp(lower, "on") == 1 ||
        strcmp(lower, "true") == 1 ||
        strcmp(lower, "off") == 1 ||
        strcmp(lower, "false") == 1;
}
References str_to_lower().
Referenced by WS_Core::Args::parse_args().
str_to_bool()
bool str_to_bool (const char * str)
Definition at line 164 of file args.cpp.
{
    char* lower = (char*)malloc(sizeof(str));
    str_to_lower(str, lower);
    if(strcmp(lower, "on") == 1 ||
        strcmp(lower, "true") == 1) {
        return true;
    }
    if(strcmp(lower, "off") == 1 ||
        strcmp(lower, "false") == 1) {
        return false;
    }
}
References str_to_lower().
Referenced by WS_Core::Args::parse_args().
str_to_lower()
void str_to_lower (const char * o, char * n)
Definition at line 157 of file args.cpp.
{
    strcpy(n, o);
    for(int i = 0; i < strlen(n); i++) {
        n[i] = tolower(o[i]);
    }
}
Referenced by str_is_bool(), and str_to_bool().