WeatherStack Core: src/core/main.cpp File Reference
main.cpp File Reference
#include <crow.h>
#include <ws_core/ws.h>
#include <ws_core/utils.h>
#include <ws_core/help.h>
#include <ws_core/types/args.h>
Macros
#define ENV(x)
#define ENVD(x, y)
#define ENVS(x, y, z)
#define ENVSV(x, y)
Functions
int main (int argc, char *const argv[])
Macro Definition Documentation
ENV
#define ENV (x)
Value:
Args::get_value(x)
Definition at line 28 of file main.cpp.
Referenced by main().
ENVD
#define ENVD (x, y)
Value:
Args::get_value(x, y)
Definition at line 29 of file main.cpp.
ENVS
#define ENVS (x, y, z)
Value:
Args::set_value(x, y, z)
Definition at line 30 of file main.cpp.
Referenced by main().
ENVSV
#define ENVSV (x, y)
Value:
Args::set_value(x, y)
Definition at line 31 of file main.cpp.
Function Documentation
main()
int main (int argc, char *const argv[])
Todo
Add something here so that the above internal API can run async
Definition at line 33 of file main.cpp.
{
    // Fetch environment variables
    const int PORT = std::stoi(Utils::GetEnv("PORT", "8000"));
    const int INTERNAL_PORT = std::stoi(Utils::GetEnv("INTERNAL_PORT", "5000"));
    // Set environment variables into arguments
    ENVS("PORT", PORT, true);
    ENVS("INTERNAL_PORT", INTERNAL_PORT, true);
    // Parse arguments
    // Arguments can (sometimes) override environment variables
    Args::parse_args(argc, argv);
    // Check for verbose/debug, output info if needed
    Args::debug_log_values();
    // Before doing anything, check to see some basic flags
    // --version, -v        Display version information
    // --help, -h           Display very basic help information
    if(ENV("VERSION").value.flag == true) {
        printf(
            "WeatherStack Core - Version %d.%d.%d\n",
            VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH
        );
        return 0;
    }
    if(ENV("HELP").value.flag == true) {
        // Display basic help information
        Help::print_usage_info();
        return 0;
    }
    // Create Crow app
    crow::SimpleApp app;
    crow::SimpleApp internal_app;
    // Register all routes
    CROW_ROUTE(app, "/").methods(crow::HTTPMethod::GET)([](const crow::request& req) {
        std::string res = "Welcome to WeatherStack Core!";
        return res;
    });
    // Internal information API route
    CROW_ROUTE(internal_app, "/").methods(crow::HTTPMethod::GET)([](const crow::request& req) {
        crow::json::wvalue response;
        response["version"] = STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH);
        response["name"] = "WeatherStack Core Internal API";
        response["repository"] = "https://github.com/WeatherStack/Core";
        response["message"] = "Number 5 is alive!";
        response["success"] = true;
        response["code"] = 200;
        return response;
    });
    // Begin listening
    std::future<void> app_future = app.port(ENV("PORT").value.integer).multithreaded().run_async();
    internal_app.port(ENV("INTERNAL_PORT").value.integer).multithreaded().run();
    /// @todo Add something here so that the above internal API can run async
    return 0;
}
References WS_Core::Args::debug_log_values(), ENV, ENVS, WS_Core::Utils::GetEnv(), WS_Core::Args::parse_args(), WS_Core::Help::print_usage_info(), STR, VERSION_MAJOR, VERSION_MINOR, and VERSION_PATCH.