WeatherStack Core: WS_Core::Args Namespace Reference
WS_Core::Args Namespace Reference
Classes
struct Arg
struct Value
Typedefs
typedef enum Type type
typedef struct Arg Arg
typedef struct Value Value
Enumerations
enum Type
Functions
bool parse_args (int argc, char *const argv[])
Parse arguments.
Value get_value (const char *key, Value def)
Attempts to get the value.
Value get_value (const char *key)
Attempts to get the value.
void set_value (const char *key, Arg::Default val, Type type)
Sets a value.
void set_value (const char *key, bool flag)
void set_value (const char *key, int val, bool port)
void set_value (const char *key, const char *string, bool path)
void set_value (const char *key, float flt)
void set_value (const char *key, double dbl)
void debug_log_values ()
Variables
const char * TypeNames []
std::array< Arg, 6 > args
std::map< const char *, Value, compare_strings > values
Typedef Documentation
Arg
typedef struct Arg WS_Core::Args::Arg
Definition at line 88 of file args.h.
type
typedef enum Type WS_Core::Args::type
Definition at line 32 of file args.h.
Value
typedef struct Value WS_Core::Args::Value
Definition at line 97 of file args.h.
Enumeration Type Documentation
Type
enum WS_Core::Args::Type
Definition at line 29 of file args.h.
                  {
            WS_CORE_ARG_TYPE(TO_ENUM)
        };
Function Documentation
debug_log_values()
void WS_Core::Args::debug_log_values ()
Definition at line 460 of file args.cpp.
{
    printf("Current argument values:\n");
    for(auto it = values.begin(); it != values.end(); it++) {
        printf("%s\n\t", it->first);
        printf("Type:    %d (%s)\n\t", it->second.type, TypeNames[it->second.type]);
        printf("Value:   ");
        switch(it->second.type) {
            case FLAG:
                printf(it->second.value.flag ? "true" : "false");
                break;
            case INTEGER:
            case PORT:
                printf("%d", it->second.value.integer);
                break;
            case STRING:
            case PATH:
                printf(it->second.value.string);
                break;
            case FLOAT:
                printf("%d", it->second.value.flt);
                break;
            case DOUBLE:
                printf("%d", it->second.value.dbl);
                break;
        }
        printf("\n\tDefault: %s", it->second.using_default ? "true" : "false");
        printf("\n\tSuccess: %s\n", it->second.success ? "true" : "false");
        printf("\n");
    }
}
References TypeNames, and values.
Referenced by main().
get_value() [1/2]
Args::Value WS_Core::Args::get_value (const char * key)
Attempts to get the value.
Parameters
key The key
Warning
Only use this if you know for certain that there is a vaue
Returns
The found value
Definition at line 412 of file args.cpp.
{
    auto i = values.find(key);
    if(i == values.end()) {
        Args::Value val;
        val.success = false;
        return val;
    }
    Args::Value _val = i->second;
    _val.success = true;
    return _val;
}
References WS_Core::Args::Value::success, and values.
get_value() [2/2]
Args::Value WS_Core::Args::get_value (const char * key, Value def)
Attempts to get the value.
Parameters
key The key
def The default value as a backup
Returns
The found (or default) value
Definition at line 400 of file args.cpp.
{
    auto i = values.find(key);
    if(i == values.end()) {
        def.using_default = true;
        return def;
    } else {
        Value val = values[key];
        val.using_default = false;
        return val;
    }
}
References WS_Core::Args::Value::using_default, and values.
parse_args()
bool WS_Core::Args::parse_args (int argc, char *const argv[])
Parse arguments.
Parameters
argc Argument count
argv Argument values
Returns
Success or not
Todo
Path implementation
Todo
Port implementation
Definition at line 264 of file args.cpp.
{
    Arg current_arg;
    // Implement default values
    for(int i = 0; i < args.size(); i++) {
        values[args[i].internal_name] = Value {
            .value = args[i].def,
            .type = args[i].arg_type,
            .using_default = true,
            .success = true
        };
    }
    for(int i = 1; i < argc; i++) {
        if(find_arg(argv[i], &current_arg)) {
            printf("%s %s\n", argv[i], TypeNames[current_arg.arg_type]);
            switch(current_arg.arg_type) {
                case FLAG:
                    if(i > argc - 1) {
                        // Check to see if it is a form of boolean
                        if(str_is_bool(argv[i + 1])) {
                            bool val = str_to_bool(argv[i + 1]);
                            Args::set_value(
                                current_arg.internal_name,
                                val
                            );
                            i++;
                        }
                    }
                    // Maybe in the future warn the user
                    // that specifying a flag that is by
                    // default true, without specifying
                    // false will do nothing
                    Args::set_value(
                        current_arg.internal_name,
                        true
                    );
                    break;
                case INTEGER:
                    if(i == argc - 1) {
                        // Invalid arguments
                        return false;
                    }
                    Args::set_value(
                        current_arg.internal_name,
                        std::atoi(argv[i + 1]),
                        false
                    );
                    i++;
                    break;
                case STRING:
                    if(i == argc - 1) {
                        // Invalid arguments
                        return false;
                    }
                    Args::set_value(
                        current_arg.internal_name,
                        argv[i + 1],
                        false
                    );
                    i++;
                    break;
                case FLOAT:
                    if(i == argc - 1) {
                        // Invalid arguments
                        return false;
                    }
                    Args::set_value(
                        current_arg.internal_name,
                        std::atof(argv[i + 1]),
                        false
                    );
                    i++;
                    break;
                case DOUBLE:
                    if(i == argc - 1) {
                        // Invalid arguments
                        return false;
                    }
                    Args::set_value(
                        current_arg.internal_name,
                        std::atof(argv[i + 1]),
                        false
                    );
                    i++;
                    break;
                case PATH:
                    // Need to check that the path is valid
                    // even if the file/directory it is pointed
                    // at does not exist
                    /// @todo Path implementation
                    break;
                case PORT:
                    // This one is a little special
                    // It needs checking to ensure
                    // that it is within valid port
                    // ranges
                    // And isn't something silly
                    /// @todo Port implementation
                    if(i == argc - 1) {
                        // Invalid arguments
                        return false;
                    }
                    auto port = strtol(argv[i + 1], nullptr, 10);
                    // Do checks
                    if(port >= 255 && port <= 65535) {
                        Args::set_value(
                            current_arg.internal_name,
                            port,
                            true
                        );
                    } else {
                        // Error, invalid port
                    }
                    i++;
                    break;
            }
        } else {
            // It couldn't find the argument
            // Failed to parse arguments
            return false;
        }
        printf("\n");
    }
    return true;
}
References WS_Core::Args::Arg::arg_type, args, find_arg(), WS_Core::Args::Arg::internal_name, set_value(), str_is_bool(), str_to_bool(), TypeNames, and values.
Referenced by main().
set_value() [1/6]
void WS_Core::Args::set_value (const char * key, Arg::Default val, Type type)
Sets a value.
Parameters
key The key
val The value
type the type
Definition at line 424 of file args.cpp.
{
    values[key].value = val;
    values[key].type = type;
}
References values.
Referenced by parse_args(), set_value(), set_value(), set_value(), set_value(), and set_value().
set_value() [2/6]
void WS_Core::Args::set_value (const char * key, bool flag)
Definition at line 429 of file args.cpp.
{
    Arg::Default val;
    val.flag = flag;
    set_value(key, val, Type::FLAG);
}
References WS_Core::Args::Arg::Default::flag, and set_value().
set_value() [3/6]
void WS_Core::Args::set_value (const char * key, const char * string, bool path)
Definition at line 441 of file args.cpp.
{
    Arg::Default val;
    val.string = (char*)malloc(sizeof(string));
    strcpy(val.string, string);
    set_value(key, val, path ? Type::PATH : Type::STRING);
}
References set_value(), and WS_Core::Args::Arg::Default::string.
set_value() [4/6]
void WS_Core::Args::set_value (const char * key, double dbl)
Definition at line 454 of file args.cpp.
{
    Arg::Default val;
    val.dbl = dbl;
    set_value(key, val, Type::DOUBLE);
}
References WS_Core::Args::Arg::Default::dbl, and set_value().
set_value() [5/6]
void WS_Core::Args::set_value (const char * key, float flt)
Definition at line 448 of file args.cpp.
{
    Arg::Default val;
    val.flt = flt;
    set_value(key, val, Type::FLOAT);
}
References WS_Core::Args::Arg::Default::flt, and set_value().
set_value() [6/6]
void WS_Core::Args::set_value (const char * key, int val, bool port)
Definition at line 435 of file args.cpp.
{
    Arg::Default _val;
    _val.integer = val;
    set_value(key, _val, port ? Type::PORT : Type::INTEGER);
}
References WS_Core::Args::Arg::Default::integer, and set_value().
Variable Documentation
args
std::array< Arg, 6 > WS_Core::Args::args
Definition at line 38 of file args.cpp.
{
        Arg {
            .name = "External Port",
            .desc = "The external port",
            .internal_name = "PORT",
            .def = {
                .integer = 8080
            },
            .ranges = {
                .integer = {
                    .min = 255,
                    .max = 65535
                }
            },
            .has_range = true,
            .arg_long = "port",
            .arg_short = "p",
            .arg_type = PORT
        },
        Arg {
            .name = "Internal Port",
            .desc = "The internal port",
            .internal_name = "INTERNAL_PORT",
            .def = {
                .integer = 5000
            },
            .ranges = {
                .integer = {
                    .min = 255,
                    .max = 65535
                }
            },
            .has_range = true,
            .arg_long = "port",
            .arg_short = "Ip",
            .arg_type = PORT
        },
        Arg {
            .name = "Version",
            .desc = "Display version information",
            .internal_name = "VERSION",
            .def = {
                .flag = false
            },
            .has_range = false,
            .arg_long = "version",
            .arg_short = "v",
            .arg_type = FLAG
        },
        Arg {
            .name = "Help",
            .desc = "Display usage information",
            .internal_name = "HELP",
            .def = {
                .flag = false
            },
            .has_range = false,
            .arg_long = "help",
            .arg_short = "h",
            .arg_type = FLAG
        },
        Arg {
            .name = "Verbose",
            .desc = "Display all information",
            .internal_name = "VERBOSE",
            .def = {
                .flag = false
            },
            .has_range = false,
            .arg_long = "verbose",
            .arg_short = "vB",
            .arg_type = FLAG
        },
        Arg {
            .name = "Debug",
            .desc = "Display debug information",
            .internal_name = "DEBUG",
            .def = {
                .flag = false
            },
            .has_range = false,
            .arg_long = "debug",
            .arg_short = "d",
            .arg_type = FLAG
        }
    };
Referenced by find_arg(), parse_args(), and WS_Core::Help::print_usage_info().
TypeNames
const char * WS_Core::Args::TypeNames
Initial value:
= {
    }
Definition at line 34 of file args.cpp.
{
        WS_CORE_ARG_TYPE(TO_STR)
    };
Referenced by debug_log_values(), and parse_args().
values
std::map< const char *, Value, compare_strings > WS_Core::Args::values
Definition at line 154 of file args.cpp.
Referenced by debug_log_values(), get_value(), get_value(), parse_args(), and set_value().